### PR TITLE
Adding conditional withMetaData on sharp

### PR DESCRIPTION
**Pull request by ShahoG**
When doing thumbnails on images sometimes the EXIF data is needed on the thumbnail especially for some cases when the orientation is needed to properly display the image properly. For this Sharp has a flag that increases the thumbnail size a bit but keeps the EXIF. With this PR I intend to give the user that option to keep the EXIF

For reference: [sharp docs](https://sharp.pixelplumbing.com/api-output#withmetadata)

### CODE REVIEW

**Review by workatease — APPROVED** [review]

**Comment by benob** [comment]
Wouldn't it make sense to add an option to rotate the thumbnail with Sharp if orientation is given in the EXIF data?

**Comment by workatease** [comment]
Or use use sharp

> Wouldn't it make sense to add an option to rotate the thumbnail with Sharp if orientation is given in the EXIF data?

Or we can also use the default rotate available in sharp library as below
`sharp(imageBuffer,failOnError).
rotate().
resize(`

**Comment by ShahoG** [comment]
I think it's ok to allow the user to do the rotation on their side. Adding rotation should be a different PR through

**Comment by workatease** [comment]
> I think it's ok to allow the user to do the rotation on their side. Adding rotation should be a different PR through

I agree with you

**Review by onildoaguiar — APPROVED** [review]

**Comment by onildoaguiar** [comment]
@ShahoG @workatease Thank you guys for the contribution!

**Pull request merged**
